export { default as Greet } from './Greet'
export { default as Person } from './Person'
export { default as Group } from './Group'
export { default as Status } from './Status'
export { default as Heading } from './Heading'
export { default as Oscar } from './Oscar'
export { default as Button } from './Button'
export { default as Input } from './Input'
export { default as Container } from './Container'
export {  ClassComponent } from './ClassComponent'
export {  default as Profile } from './Profile'
export {  default as ComponentProp } from './ComponentProp'
export {  default as Ristricted } from './Ristricted'
export {  default as TemplateLiterals } from './TemplateLiterals'
export {  default as ComponentProps } from './ComponentProps'
export {  default as Polymorphism } from './Polymorphism'
export {  GenericType}  from './GenericType'